baseURL: "/"
languageCode: "en-us"
title: "hophamlam"
theme: "PaperMod"

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

params:
  env: production
  title: hophamlam
  description: "Personal Blog"
  keywords: ["Blog", "Portfolio", "PaperMod"]
  author: hophamlam
  DateFormat: "January 2, 2006"
  defaultTheme: auto
  disableThemeToggle: false
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false
  googleAnalytics: ""

  profileMode:
    enabled: true
    title: "hophamlam"
    subtitle: "Welcome to my blog"
    imageUrl: "https://gravatar.com/avatar/8bcd691b08c9cd64eb566272afee38c4?size=512"
    imageWidth: 120
    imageHeight: 120
    imageTitle: "hophamlam"

  socialIcons:
    - name: "telegram"
      url: "https://t.me/hophamlam"
    - name: "facebook"
      url: "https://facebook.com/hophamlam"
    - name: "zalo"
      url: "https://zalo.me/hophamlam"
    - name: "messenger"
      url: "https://m.me/hophamlam"
    - name: "hashnode"
      url: "https://hashnode.com/@hophamlam"

  assets:
    favicon: "/favicon.ico"
    favicon16x16: "/favicon-16x16.png"
    favicon32x32: "/favicon-32x32.png"
    apple_touch_icon: "/apple-touch-icon.png"
    safari_pinned_tab: "/safari-pinned-tab.svg"

menu:
  main:
    - identifier: "categories"
      name: "Categories"
      url: "/categories/"
      weight: 10
    - identifier: "tags"
      name: "Tags"
      url: "/tags/"
      weight: 20
    - identifier: "archives"
      name: "Archives"
      url: "/archives/"
      weight: 30
